FacebookApplicationUsingGraphAPI/FacebookApplicationUsingGraphAPI/Controllers/PostSearchController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Facebook;
using FacebookApplicationUsingGraphAPI.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace FacebookApplicationUsingGraphAPI.Controllers
{
    public class PostSearchController : Controller
    {
        facebookDBEntities db = new facebookDBEntities();
        private static string accessToken = "CAACEdEose0cBACWZCmMXMZBrHR71lZBcGfYr42eHgnP07XvZBgJ7FDK4LZBh68zaoUBrFIU4j2QtAsc33j6oalDRWDeZCnyhjh8jIEgecloo3FpTcr9SSABKMWZBdZAiZCRdm3bfC8qZCnIMC1COm9HNx9srXe5ZBPsPUcxBYb6XZAkOD1B3Sap3UxCVuvsvw0oswLlZAB3RK04M9DBlCOUXmmxzYn4909WOHxzsZD";
        FacebookClient client = new FacebookClient(accessToken);
        //
        // GET: /PostSearch/
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult PageInfo()
        {
            
            //var client = new FacebookClient(accessToken);
            dynamic me = client.Get("me?fields=id,email,first_name,last_name,gender,picture");
            FacebookUserModel fmodel = Newtonsoft.Json.JsonConvert.DeserializeObject<FacebookUserModel>(me.ToString());
            return View(fmodel);


        }

        public ActionResult FacebookPages()
        {
            ManagePageByUser aManagePageByUser = new ManagePageByUser();
            
            //var client = new FacebookClient(accessToken);

            dynamic me = client.Get("me/accounts?fields=id,name,category");
            var data = me["data"].ToString();
            aManagePageByUser.pageList = JsonConvert.DeserializeObject<List<FacebookUserPage>>(data);
            return View(aManagePageByUser);
        }


       


        //Here SelectedPage ID is Not Passing......
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FacebookPages(string pageId)
        {
            ManagePageByUser aManagePageByUser = new ManagePageByUser();

            //var client = new FacebookClient(accessToken);

            dynamic me = client.Get("me/accounts?fields=id,name,category");
            var data = me["data"].ToString();
            dynamic pageName = client.Get(pageId + "?fields=name,likes");
            string pname = pageName.ToString();
            JObject rss = JObject.Parse(pname);
            ViewBag.PageNameById = (string) rss.SelectToken("name");
            ViewBag.PageLikesById = (int)rss.SelectToken("likes");
            aManagePageByUser.pageList = JsonConvert.DeserializeObject<List<FacebookUserPage>>(data);
            try
            {
                ViewBag.PostsList = GetPage(pageId).postLists.ToList();
                return View(aManagePageByUser);
            }
            catch (NullReferenceException exception)
            {
                ViewBag.PostsList = null;
                return View(aManagePageByUser);
            }
        }


        public int GetNoOfLikesInPost(string postId)
        {
            //var client = new FacebookClient(accessToken);

            dynamic me = client.Get(postId+"?fields=likes.summary(true)");
            string msg = me.ToString();
            JObject rss = JObject.Parse(msg);
            try
            {
                int totalLikes = (int) rss.SelectToken("likes.summary.total_count");
                return totalLikes;
            }
            catch (ArgumentNullException exception)
            {
                return 0;
            }
        }

        public int GetNoofShares(string postId)
        {
            //var client = new FacebookClient(accessToken);

            dynamic me = client.Get(postId + "?fields=shares");
            string msg = me.ToString();
            JObject rss = JObject.Parse(msg);
            try
            {
                int totalShare = (int) rss.SelectToken("shares.count");
                return totalShare;
            }
            catch (ArgumentNullException exception)
            {
                return 0;
            }
        }

        public string GetPostMessage(string postId)
        {
           // var client = new FacebookClient(accessToken);

            dynamic me = client.Get(postId + "?fields=message");
            string msg = me.ToString();
            JObject rss = JObject.Parse(msg);
            string message = (string)rss.SelectToken("message");
            return message;
        }

        public List<User> GetLikers(string postId)
        {
           // var client = new FacebookClient(accessToken);
            dynamic me = client.Get(postId + "?fields=likes{id,name,picture}");
            string msg = me.ToString();
            JObject rss = JObject.Parse(msg);
            int noOfLikes = GetNoOfLikesInPost(postId);
            List<User> users = new List<User>();
            for (int i = 0; i < noOfLikes; i++)
            {
                string name = (string) rss.SelectToken("likes.data["+i+"].name");
                string id = (string)rss.SelectToken("likes.data[" + i + "].id");
                string picture = (string) rss.SelectToken("likes.data["+i+"].picture.data.url");
                users.Add(
                        new User()
                        {
                            Id  = id,
                            Name = name,
                            Picture = picture
                        }
                    );
            }

            return users;


        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult GetPagePosts(string pageId)
        {
           
            dynamic me = client.Get(pageId + "?fields=posts{message,likes{id,name,picture}}");
            string msg = me.ToString();
            JObject rss = JObject.Parse(msg);
            List<Post> posted = new List<Post>();
            List<User> users = new List<User>();
           
            //Working Correctly............
           // string message = (string) rss.SelectToken("posts.data[0].likes.data[0].name");
            //-------------------------------------------
            for (int i = 0; i < rss.Count + 1; i++)
            {
                string message = (string)rss.SelectToken("posts.data[" + i + "].message");
                // string picture = (string)rss.SelectToken("posts.data[0].likes.data[0].pic_square");
                string name = (string)rss.SelectToken("posts.data[" + i + "].likes.data[" + i + "].name");

                posted.Add(
                        new Post()
                        {
                            ContainText = message,
                            Users = users
                        }
                    );
            }

            
            
            
            return Json(posted, JsonRequestBehavior.AllowGet);
        }

       public AdminPost GetPage(string pageId)
       {
           
           AdminPost adminPost = new AdminPost();
           //var client = new FacebookClient(accessToken);
           string query = pageId+"?fields=posts{message}";
           dynamic me = client.Get(query);
           try
           {
               var data = me["posts"]["data"].ToString();
               adminPost.postLists = JsonConvert.DeserializeObject<List<UserPosts>>(data);
               return adminPost;
           }
           catch (KeyNotFoundException exception)
           {
               return null;
           }

       }

       // [HttpPost]
        //[ValidateAntiForgeryToken]
       public ActionResult GetPostDetails(string postId)
        {
            List<User> likersList = GetLikers(postId);
            int NoOfLikes = GetNoOfLikesInPost(postId);
            string Message = GetPostMessage(postId);
            int NoOfShares = GetNoofShares(postId);


            ViewBag.Message = Message;
            ViewBag.NoOfLikes = NoOfLikes;
            ViewBag.LikersList = likersList;
            ViewBag.NoOfShares = NoOfShares;
            return View();

        }

        public JsonResult GetData(string postId)
        {
            int id = postId.IndexOf('_');
            string postShared = postId.Substring(id + 1);
            //GetSharerId(postShared,GetNoofShares(postId));

            return Json( GetSharerId(postShared,GetNoofShares(postId)), JsonRequestBehavior.AllowGet);
        }

        public string GetPostShareId(string postId)
        {
            int id = postId.IndexOf('_');
            string postShared = postId.Substring(id + 1);
            //GetSharerId(postShared,GetNoofShares(postId));

            return postShared;
        }

        public List<Share> GetSharerId(string postShared, int noOfShares)
        {
            dynamic me = client.Get(postShared + "/sharedposts");
            string msg = me.ToString();
            JObject rss = JObject.Parse(msg);
            List<Share> sharerList = new List<Share>();
           

            for (int i = 0; i < noOfShares; i++)
            {
                Share aShare = new Share();
                aShare.SharerId = (string) rss.SelectToken("data["+i+"].from.id");
                sharerList.Add(aShare);
            }
            return sharerList;
        }

        
        public bool IsLikeThisPost(string userId, string postId)
        {
            
            List<User> user = GetLikers(postId);
            var result = user.Where(a => a.Id == userId);
            if (result.Any())
            {
                return true;
            }
            else
            {
                return false;
            }
                
        
        }

        public bool IsSharedThisPost(string userId, string postId)
        {
            string postShared = GetPostShareId(postId);
            int noOfShares = GetNoofShares(postId);
            List<Share> shareList = GetSharerId(postShared, noOfShares);
            var user = shareList.Where(a => a.SharerId == userId);
            if (user.Any())

FacebookApplicationUsingGraphAPI/FacebookApplicationUsingGraphAPI/Views/PostSearch/FacebookPages.cshtml
@model FacebookApplicationUsingGraphAPI.Models.ManagePageByUser

@{
    ViewBag.Title = "FacebookPages";
}

<h2>Facebook Pages</h2><hr>
@using (Html.BeginForm("FacebookPages", "PostSearch", FormMethod.Post))

{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label>Page Name</label>
        <select name="pageId"  id="pageId" class="form-control">
            @foreach (var page in Model.pageList)
            {

                <option value="@page.id">@page.name</option>

            }

           
        </select>
    </div>
    
   <div class="form-group">
        <input class="btn btn-success" type="submit" value="Search Posts">
    </div>
}

@if (ViewBag.PageNameById != null)
{
    <h3 id="pageNameById">@ViewBag.PageNameById</h3>
}
@if (ViewBag.PageLikesById != null)
{
    <h3>Likes: @ViewBag.PageLikesById</h3>
}


@if (ViewBag.Error != null)
{
    <h3>@ViewBag.Error</h3>
}

@if (ViewBag.PostsList != null)
{
    <div id="postsList">
        
        @*@using (Html.BeginForm("GetPostDetails","PostSearch",FormMethod.Post))
        {*@
           
             @Html.AntiForgeryToken()
             
            @foreach (var post in ViewBag.PostsList)
            {
                
                if (post.message != null)
                {
                    
                    <div class="jumbotron" id="single_post">
                        <p>
                            @post.message

                            
                        </p>
                        
                       
                        
                       
                        <input type="button" id="saveInDatabase" class="btn btn-success" value="Save in Database">
                        @*<input type="hidden" id= "postId" name="postId" value=@post.id>*@
                        @Html.ActionLink("View Details", "GetPostDetails",new { postId = post.id },new{@class="btn btn-primary"})
                        @Html.ActionLink("Save", "SaveInDatabase", new { postId = post.id }, new { @class = "btn btn-danger" })
                       

                        
                    </div>
                }


            }
        @*}*@
        
    

    </div>
}
else{
    <p>Sorry! There is no post found in this page!</p>
}
    
<ul id="shareid">
    
</ul>

@*<table class="table table-bordered table-striped">
    <tr>
        <th>Page ID</th>
        <th>Page Title</th>
        <th>Category</th>
    </tr>
    @foreach (var page in Model.pageList)
    {
        <tr><td>@page.id</td><td>@page.name</td><td>@page.category</td></tr>
    }
</table>*@


<script>    

    $("#details").click(function() {

        var post = $("#postdetails").val();
        alert(post);
    });

    $("#saveInDatabase").click(function() {

        //var id = $("#postId").val();
        //$.ajax({
        //    type: "POST",
        //    url: "/PostSearch/GetData",
        //    data: id,
        //    datatype: "json",
        //    success: function (data) {
        //        alert(id);
        //    }
        //});
        var id = $("#postId").val();
        alert(id);
        var json = { postId: id };
        $.ajax({
            type: "POST",
            url: '@Url.Action("GetData", "PostSearch")',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify(json),
            dataType: "json",
            success: function (data) {

                $.each(data, function(key, value) {

                    $("#shareid").append('<li>'+value+'</li>');
                });

            },

        });
        




    });

</script>

FacebookApplicationUsingGraphAPI/FacebookApplicationUsingGraphAPI/Views/PostSearch/GetPostDetails.cshtml
@using System.Web.UI.WebControls

@{
    ViewBag.Title = "GetPostDetails";
}

<h2>GetPostDetails</h2><hr>

<div class="jumbotron">
    @ViewBag.Message
</div><hr>

<p><span class="label label-success">Likes:</span> @ViewBag.NoOfLikes | <span class="label label-primary">Shares:</span> @ViewBag.NoOfShares</p>
<div id="user" class="row">
    
    @if (ViewBag.NoOfLikes != null)
    {
        <p>Who Likes This? </p>
    }
    
    <hr>
    @foreach (var user in ViewBag.LikersList)
    {
        <div class="col-lg-1">
            <img src="@user.Picture" />
            <p>@user.Name</p>
        </div>


    }

</div>

FacebookApplicationUsingGraphAPI/FacebookApplicationUsingGraphAPI/Views/PostSearch/Index.cshtml
@{
    ViewBag.Title = "Post Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Post Search</h2><hr>

@using (Html.BeginForm())
{
     <div>
            <label>
                Created Date
            </label>

            @Html.TextBox("txtCreatedDate",null,new{@class="form-control"})
        </div>
        <div>
            <label>
                Contain Text
            </label>

            @Html.TextBox("txtContainText",null,new{@class="form-control"})
        </div>
            <br>
        <div>                   
            <input id="btnSearch" type="button" value="Search" onclick="PostStatus();" class="btn btn-success" />
        </div>
    
}


    <div id="pageDetails">
       
            <h2>Post Title: </h2>
            <p></p>
        
        
        
    </div>

    <select id ="pageName">
        <option value="">Dhaka</option>
        <option value="">Rajshahi</option>
        <option value="">Khulna</option>
    </select>




    <script type="text/javascript">

        //$(function () {
            

        //            //$.ajax({
        //            //    url: '/PostSearch/PageInfo',
        //            //    type: 'GET',
        //            //    contentType: "application/json; charset=utf-8",
        //            //    data: JSON.stringify(json),
        //            //    dataType: "json",
        //            //    success: function (data) {
        //            //        //$.each(data, function(key, value) {

        //            //        //    options += '<option value="' + key + '">' + value + '</option>';                    


        //            //        //});
        //            //        alert("Hi THere"+data.name);

        //            //        // $("select#pageName").html(options);
        //            //    }
        //    //});

        //    alert("HI");              
            

        //});

       
            $("#pageName").change(function () {

                alert("HEllo There");
            });


        


</script>    

FacebookApplicationUsingGraphAPI/FacebookApplicationUsingGraphAPI/Views/PostSearch/PageInfo.cshtml
@model FacebookApplicationUsingGraphAPI.Models.FacebookUserModel

@{
    ViewBag.Title = "PageInfo";
}

<h2>PageInfo</h2>



<table class="table table-striped table-bordered">
    <tr><td>Picture</td><td><img src='@Model.picture.data.url' /></td></tr>
    <tr><td>Facebook Id</td><td>@Model.id</td></tr>
    
    <tr><td>First Name</td><td>@Model.first_name</td></tr>
    <tr><td>Last Name</td><td>@Model.last_name</td></tr>
    <tr><td>Gender</td><td>@Model.gender</td></tr>
    
</table>